services:
  php:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    volumes:
      - lunch-app:/var/www/html
      - lunch-database:/var/www/database
    networks:
      - lunch-network

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - lunch-app:/var/www/html:ro
    networks:
      - lunch-network
    depends_on:
      - php

  certbot:
    image: certbot/certbot:latest
    command: renew --dry-run
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - lunch-network

networks:
  lunch-network:
    driver: bridge

volumes:
  lunch-app:
  lunch-database:
